"""initial_schema

Revision ID: bc34fd41671a
Revises:
Create Date: 2026-05-29 15:43:45.331391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc34fd41671a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("limit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("available", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("rewards_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "statement_balance", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("statement_due_day_of_month", sa.Integer(), nullable=True),
        sa.Column("payment_account_ref", sa.Integer(), nullable=True),
        sa.Column("as_of_date", sa.String(), nullable=True),
        sa.Column("minimum_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("partial_account_number", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("asset_ref", sa.Integer(), nullable=True),
        sa.Column("interest_rate", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("next_due_date", sa.String(), nullable=True),
        sa.Column("as_of_date", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "budget_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("recurrence", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("day_of_year", sa.Integer(), nullable=True),
        sa.Column("continuous", sa.Boolean(), nullable=True),
        sa.Column("auto_account_ref", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshots")
    op.drop_table("budget_entries")
    op.drop_table("asset_entries")
    op.drop_table("accounts")
    # ### end Alembic commands ###
